apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/affinity: local
    service.cilium.io/global: "true"
  name: echo-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo-server
  sessionAffinity: None
  type: ClusterIP
